import os

APP_SECRET_KEY = os.environ["FLASK_APP_SECRET_KEY"]
GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_PROVIDER_AUTHENTICATION_SECRET"]

DB_SERVER_NAME = os.environ["DB_SERVER_NAME"]
DB_DRIVER_NAME = os.environ["DB_DRIVER_NAME"]
DB_NAME = os.environ["DB_NAME"]
DB_USERNAME = os.environ["DB_USERNAME"]
DB_PASSWORD = os.environ["DB_PASSWORD"]

STORAGE_ACCOUNT_NAME = os.environ["STORAGE_ACCOUNT_NAME"]
STORAGE_ACCOUNT_KEY = os.environ["STORAGE_ACCOUNT_KEY"]
CONTAINER_NAME = os.environ["CONTAINER_NAME"]